#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate the Vitrin OS brand assets from their geometry.

This script is the source of the marks in this directory: the SVGs and PNGs
alongside it are build output, regenerated by running

    python3 assets/brand/generate.py

Note the split, which is deliberate and matches the repository's own rules:
*this script* is Apache-2.0 like the rest of the repository's tooling, while
the *marks it emits* are trademarks and are not licensed by it. See
`assets/brand/README.md` and the root `TRADEMARK.md`.

Construction
------------
The mark is a four-blade iris. Each blade is one straight inner edge -- a
side of the square opening -- plus an outer arc, which is the geometry that
actually reads as an aperture; a disc with slits cut out of it does not.
`TWIST` rotates the opening against the blade divisions to produce the
pinwheel a real iris has. Gaps are specified as distances rather than
angles so a slit is the same width at the rim as at the opening.

The square opening is the point of departure from a camera aperture: it is a
screen. Scoped visibility onto a surface, which is what the project does.
"""
import math
import subprocess
from pathlib import Path

# The accent is not an arbitrary brand colour: it is the accent the trusted
# core paints its own consent card with, in
# crates/vitrin-core/src/consent/render.rs.
ACCENT = "#4D9DE0"
INK = "#0C1116"
PAPER = "#FFFFFF"

R = 92.0        # outer radius
TWIST = 24.0    # opening rotation against the blade divisions, degrees
HERE = Path(__file__).parent


def polar(rad, deg):
    a = math.radians(deg)
    return (rad * math.cos(a), rad * math.sin(a))


def pt(p):
    return f"{p[0]:.2f},{p[1]:.2f}"


def blades(n=4, r=48.0, rim_gap=9.0, inner_gap=9.0, twist=TWIST, start=-90.0):
    """One path per blade. Gaps are user-unit distances, not angles."""
    step = 360.0 / n
    gdeg = math.degrees(rim_gap / R)     # arc length -> degrees at radius R
    out = []
    for k in range(n):
        b = start + k * step
        h0, h1 = polar(r, b + twist), polar(r, b + step + twist)
        dx, dy = h1[0] - h0[0], h1[1] - h0[1]
        length = math.hypot(dx, dy)
        ux, uy = dx / length, dy / length
        h0 = (h0[0] + ux * inner_gap, h0[1] + uy * inner_gap)
        h1 = (h1[0] - ux * inner_gap, h1[1] - uy * inner_gap)
        o0, o1 = polar(R, b + gdeg / 2), polar(R, b + step - gdeg / 2)
        out.append(f"M{pt(h0)}L{pt(o0)}A{R:.2f},{R:.2f} 0 0 1 {pt(o1)}"
                   f"L{pt(h1)}Z")
    return out


def mark(fill=ACCENT, uid="k", round_r=6.0, **kw):
    """Blades, corners rounded by stroking, clipped to a true circle.

    The clip matters: stroking to round the inner corners also pushes the
    blade tips past the rim, which leaves spikes on the silhouette.
    """
    paths = "".join(f'<path d="{d}"/>' for d in blades(**kw))
    return (f'<clipPath id="{uid}"><circle r="{R}"/></clipPath>'
            f'<g clip-path="url(#{uid})" fill="{fill}" stroke="{fill}" '
            f'stroke-width="{round_r}" stroke-linejoin="round">{paths}</g>')


# --------------------------------------------------------------- wordmark
# Mono-line geometry, so it pairs with the mark's construction and carries
# no font dependency into the repository. Each glyph returns its paths and
# its ink edges; glyphs are then spaced on those edges with a constant
# sidebearing, which is what keeps a bare stem like 'i' optically even.
XH, STROKE, ASC, DOT, SB = 58.0, 12.0, 22.0, 18.0, 15.0


def g_v():
    w = 38.0
    return [f"M0,{-XH}L{w / 2:.1f},0L{w},{-XH}"], 0.0, w


def g_i():
    return [f"M0,{-XH}L0,0", f"M0,{-XH - DOT}L0,{-XH - DOT}"], 0.0, 0.0


def g_t():
    return [f"M0,{-XH - ASC}L0,0", f"M{-13},{-XH}L{17},{-XH}"], -13.0, 17.0


def g_r():
    return ([f"M0,{-XH}L0,0",
             f"M0,{-XH + 20:.1f}A20,20 0 0 1 {25},{-XH + 1:.1f}"], 0.0, 25.0)


def g_n():
    w = 36.0
    return ([f"M0,{-XH}L0,0",
             f"M0,{-XH + 18:.1f}A{w / 2},{w / 2} 0 0 1 {w},{-XH + 18:.1f}"
             f"L{w},0"], 0.0, w)


def g_o():
    r = XH / 2
    return ([f"M0,{-r}A{r},{r} 0 1 1 {2 * r},{-r}"
             f"A{r},{r} 0 1 1 0,{-r}Z"], 0.0, 2 * r)


def g_s():
    # Two tangent circles of radius XH/4, traced as one stroke: the upper
    # bowl counter-clockwise, the lower bowl clockwise, meeting at the waist.
    r = XH / 4
    cx = r
    up, lo = -3 * r, -r          # upper / lower circle centre y
    # Each bowl sweeps ~220 degrees, not the full circle -- a wider sweep
    # closes the bowl into a loop and the glyph reads as a 'g'.
    a0, a1 = math.radians(-50), math.radians(130)
    p0 = (cx + r * math.cos(a0), up + r * math.sin(a0))
    waist = (cx, up + r)
    p1 = (cx + r * math.cos(a1), lo + r * math.sin(a1))
    return ([f"M{pt(p0)}A{r:.2f},{r:.2f} 0 1 0 {pt(waist)}"
             f"A{r:.2f},{r:.2f} 0 1 1 {pt(p1)}"], 0.0, 2 * r)


def g_space():
    return [], 0.0, 16.0


GLYPHS = {"v": g_v, "i": g_i, "t": g_t, "r": g_r, "n": g_n,
          "o": g_o, "s": g_s, " ": g_space}


def wordmark(text="vitrin", fill=ACCENT):
    out, right = [], None
    for ch in text:
        paths, ink_l, ink_r = GLYPHS[ch]()
        x = -ink_l if right is None else right + SB - ink_l
        out += [f'<path d="{d}" transform="translate({x:.1f},0)"/>'
                for d in paths]
        right = x + ink_r
    return (f'<g fill="none" stroke="{fill}" stroke-width="{STROKE}" '
            f'stroke-linecap="round" stroke-linejoin="round">'
            f'{"".join(out)}</g>'), right


def svg(body, w, h, vx, vy, vw, vh, bg=None, title=None):
    back = (f'<rect x="{vx}" y="{vy}" width="{vw}" height="{vh}" fill="{bg}"/>'
            if bg else "")
    t = f"<title>{title}</title>" if title else ""
    return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}"'
            f' viewBox="{vx} {vy} {vw} {vh}" role="img">{t}{back}{body}</svg>')


def lockup(mark_fill=ACCENT, text_fill=INK, uid="lk", scale=0.60, gap=54.0,
           pad=14.0, bg=None, text="vitrin os"):
    wm, ww = wordmark(text, fill=text_fill)
    wx, wy = R + gap, XH * scale / 2
    body = (mark(fill=mark_fill, uid=uid)
            + f'<g transform="translate({wx},{wy}) scale({scale})">{wm}</g>')
    vx, vy = -R - pad, -R - pad
    vw, vh = (wx + ww * scale) + R + pad * 2, 2 * R + pad * 2
    if bg:
        body = (f'<rect x="{vx}" y="{vy}" width="{vw}" height="{vh}" '
                f'fill="{bg}"/>') + body
    return body, (vx, vy, vw, vh)


def social_card():
    """1280x640 GitHub social preview.

    The lockup is laid out from its *scaled* height rather than a guessed
    y-offset, so the text below it can never be overrun.
    """
    w, h = 1280, 640
    body, (vx, vy, vw, vh) = lockup(mark_fill=ACCENT, text_fill=PAPER,
                                    uid="sc")
    lx, ly = 96.0, 92.0
    lk_w = 470.0
    s = lk_w / vw
    lk_h = vh * s
    sans = "DejaVu Sans, Helvetica, Arial, sans-serif"
    mono = "DejaVu Sans Mono, monospace"
    tag = "An open-source, agent-first display server."
    subs = ("Humans and AI agents observe and operate the same GUIs, under",
            "granular, revocable, capability-scoped authorization.")
    y_tag = ly + lk_h + 92
    # A large, low-opacity mark bleeding off the right edge.
    ghost = (f'<g opacity="0.05" transform="translate(1190,326) scale(3.2)">'
             f'{mark(fill=ACCENT, uid="ghost")}</g>')
    lines = "".join(
        f'<text x="{lx}" y="{y_tag + 62 + i * 40}" fill="#8FA3B0" '
        f'font-size="27" font-family="{sans}">{t}</text>'
        for i, t in enumerate(subs))
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" '
        f'viewBox="0 0 {w} {h}" role="img">'
        f'<title>Vitrin OS</title>'
        f'<rect width="{w}" height="{h}" fill="{INK}"/>'
        f'{ghost}'
        f'<g transform="translate({lx},{ly}) scale({s:.4f}) '
        f'translate({-vx},{-vy})">{body}</g>'
        f'<text x="{lx}" y="{y_tag}" fill="{PAPER}" font-size="41" '
        f'font-family="{sans}" font-weight="600">{tag}</text>'
        f'{lines}'
        f'<rect x="{lx}" y="{h - 96}" width="76" height="5" rx="2.5" '
        f'fill="{ACCENT}"/>'
        f'<text x="{lx}" y="{h - 44}" fill="#5C7080" font-size="24" '
        f'font-family="{mono}">github.com/vitrin-os/vitrin-os</text>'
        f'</svg>')


def write(name, content):
    (HERE / name).write_text(content)
    print(f"  {name}")


def rasterise(src, out, width, height=None):
    cmd = ["rsvg-convert", "-w", str(width)]
    if height:
        cmd += ["-h", str(height)]
    cmd += [str(HERE / src), "-o", str(HERE / out)]
    subprocess.run(cmd, check=True)
    print(f"  {out}")


def main():
    print("marks:")
    write("vitrin-mark.svg",
          svg(mark(uid="m"), 256, 256, -104, -104, 208, 208,
              title="Vitrin OS"))
    # currentColor so it inherits text colour wherever it is inlined.
    write("vitrin-mark-mono.svg",
          svg(mark(fill="currentColor", uid="mm"), 256, 256,
              -104, -104, 208, 208, title="Vitrin OS"))
    # Chunkier gaps and a wider opening: the display mark's slits vanish
    # below about 24px.
    write("vitrin-favicon.svg",
          svg(mark(uid="f", r=54, rim_gap=15, inner_gap=15), 64, 64,
              -100, -100, 200, 200, title="Vitrin OS"))

    print("lockups:")
    for name, kw in (
        ("vitrin-lockup.svg", dict(text_fill=INK, uid="l1")),
        ("vitrin-lockup-dark.svg", dict(text_fill=PAPER, uid="l2")),
    ):
        body, (vx, vy, vw, vh) = lockup(**kw)
        write(name, svg(body, 960, round(960 * vh / vw), vx, vy, vw, vh,
                        title="Vitrin OS"))

    print("social card:")
    write("social-card.svg", social_card())

    print("raster:")
    rasterise("vitrin-favicon.svg", "favicon-16.png", 16, 16)
    rasterise("vitrin-favicon.svg", "favicon-32.png", 32, 32)
    rasterise("vitrin-favicon.svg", "apple-touch-icon.png", 180, 180)
    rasterise("vitrin-mark.svg", "vitrin-mark-512.png", 512, 512)
    rasterise("social-card.svg", "social-card.png", 1280, 640)


if __name__ == "__main__":
    main()
