// SPDX-License-Identifier: MPL-2.0
//! K12b -- the Landlock ruleset the realm's app inherits (P2.6.3, issue
//! #187).
//!
//! # Where this runs, and why the position is not negotiable
//!
//! Inside [`crate::exec_shim`], on PID 1 of the realm's pid namespace, in a
//! window bounded on both sides:
//!
//! - **after** `PR_SET_NO_NEW_PRIVS` (K10, [`crate::drop_all_capabilities`]),
//!   because `landlock_restrict_self` refuses without it;
//! - **after** `pivot_root` (K8), because every path below is an *in-realm*
//!   absolute path and would otherwise be resolved against the host tree;
//! - **before** K13's `close_range(4, UINT_MAX, CLOSE_RANGE_CLOEXEC)`,
//!   because every rule here is an `O_PATH` descriptor and one left unmarked
//!   is a descriptor the app inherits;
//! - **before** the `chdir` (K14), the argv assembly and the `execve`, each of
//!   which must therefore fall inside the granted set. A ruleset that forgets
//!   `/vitrin/vitrin-shim` does not fail here; it fails at `execve` with `EACCES`,
//!   which is a realm that will not start.
//!
//! Ordinary Rust is allowed (this binary is single-threaded by design -- see
//! `main.rs`'s module docs), so the grant table below is built with `Vec` and
//! `CString` rather than in async-signal-safe primitives. The three syscall
//! wrappers are nonetheless allocation-free, because [`crate::tests`] drives
//! [`add_path_rule`] and [`restrict_self`] from a forked child. [`create_ruleset`]
//! is called from the parent there -- the ledger has to read the rung off the
//! ruleset, and a child's recording dies with the child -- and keeps the
//! property anyway, because the shipped path calls all three in sequence.
//!
//! # Raw syscalls, and no `landlock` crate
//!
//! `Cargo.toml` records a **one-dependency budget** for this binary against
//! plan risk R7, and records that `rustix` was evaluated and declined. The
//! same reasoning governs here and more strongly: this is the process that
//! *builds* a realm's confinement, so every crate it links is a crate that
//! can weaken one. Three syscall numbers and two `#[repr(C)]` structs is the
//! whole surface, and `spawn/isolation.rs` already spells 444 by hand for the
//! ABI probe -- this file follows that precedent rather than inventing a
//! second one.
//!
//! # What a "rung" is, mechanically
//!
//! A Landlock ABI rung is **which bits are legal in `handled_access_fs`**
//! (plus, at rung 6, in `scoped`). The kernel refuses `EINVAL` at ruleset
//! creation for a bit above its own ABI, which has two consequences this
//! module is built on:
//!
//! 1. There is a **declared floor**, not a degradation ladder (owner's
//!    decision, 2026-08-15; [`vitrin_realm_init::LANDLOCK_MIN_ABI`]). A shipped
//!    session asks for the highest rung this build and this kernel agree on,
//!    and a kernel below the floor is **refused** -- by the core before any
//!    realm is spawned, and again by [`apply_with`] if it ever gets that far.
//!    The one-rung-at-a-time descent still exists in [`create_ruleset`] and now
//!    bottoms out at the floor; what comes back is still what the kernel
//!    granted, never what was asked for, and the core still warns when the two
//!    differ. **The floor narrowed #187 rather than completing it**; P2.6.3 was
//!    accepted on 2026-08-19 (Correction 7, D-044), and PRD §20's "coverage is
//!    kernel-dependent" caveat is answered for the five kernels #281 booted
//!    (`docs/book/src/isolation-kernels.md`) and for no others. The multi-rung table
//!    that *did* get built (`docs/book/src/isolation-matrix.md`, `cargo xtask
//!    isolation-matrix`) is generated by **parsing this file** -- the bit
//!    constants, the base mask, and each `if rung >= N` guard in
//!    [`handled_access_fs`] -- so moving a right to another rung here makes
//!    the checked-in page stale and CI red. It measures no kernel.
//!    `docs/plan/02-phase-2-semantic-epochs.md` carries both corrections.
//! 2. The **cap reproduces exactly what this build asks for on an ABI-N
//!    kernel** -- which is not the same sentence as "reproduces an ABI-N
//!    kernel", and the difference is three rungs wide. Requesting rung N on a
//!    kernel that supports M > N uses rung N's `handled_access_fs`, so each
//!    rung's absence is *measurable* instead of prose -- **for the rungs that
//!    move that mask**: 1, 2, 3, 5 and 9 move `handled_access_fs`, and 6
//!    moves `scoped`. Rungs **4, 7 and 8 do not**. Rung 4 buys
//!    `handled_access_net`, which this module deliberately leaves zero (see
//!    "What this ruleset does not do"); rungs 7 and 8 buy
//!    `landlock_restrict_self` *flags*, which [`restrict_self_flags`] passes
//!    as zero in every shipped run (the one way to move it is the
//!    [`vitrin_realm_init::LANDLOCK_AUDIT_ENV`] diagnostic, which changes what
//!    the kernel logs and nothing about what it permits). Nothing this build
//!    asks for changes across those rungs, so
//!    there is nothing for a cap to take away, and the enforced domain --
//!    `handled_access_fs`, `scoped` and the flags word together -- is
//!    **byte-identical at rungs 3 and 4** and **byte-identical at rungs 6, 7
//!    and 8**. Nine rung numbers, six distinct domains. `--landlock=abi:4`
//!    and `--landlock=abi:7` are still accepted and still journal a distinct
//!    `applied_profile`, so that string names *which rung was obtained* and
//!    never *how much confinement*; every published statement of the ladder
//!    carries the exception.
//!
//! **What rung N is not, is uniformly weaker than rung N+1.** An earlier
//! draft of this module said "the cap can only weaken"; that is false, and
//! [`REFER`] is why. A domain denies reparenting whenever its ruleset does
//! not *handle* `REFER`, so rung 1 forbids a cross-directory `rename(2)`
//! inside the realm's own writable storage and rung 2 permits it. Measured
//! here (kernel `7.1.8-arch1-3`, ABI 9, 2026-08-14): rung 1 answers `EXDEV`,
//! rungs 2..=9 succeed, and a same-directory rename succeeds at every rung.
//! **Only the first two of those rungs are re-taken by a test.**
//! `rung_one_forbids_reparenting_that_the_rung_above_permits` enters a domain
//! at rungs 1 and 2 and at no other -- it declares that in `BEHAVIOURAL_RUNGS`
//! and asserts it against the rungs it actually entered -- so rungs 3..=9
//! above, and the same-directory result at any rung but 1, are a **hand run on
//! that one date**: checked by a reader, and by nothing in CI. Do not read the
//! range as coverage; `docs/book/src/limits.md` and
//! `docs/book/src/isolation-matrix.md` draw the same line, which is why they
//! can also say no test enters a domain at rung 4 or rung 5 without
//! contradicting this paragraph.
//! The cap is a **dial**, not a one-way weakening, and every published
//! statement of it says so.
//!
//! # The consequence nobody grants their way out of: **no mounts, ever**
//!
//! A Landlock domain denies **every** mount-topology change to the sandboxed
//! process and all its descendants, unconditionally. It is not an access
//! right, so it is not in any rule and no grant enables it. Measured on this
//! box rather than read: with **all** rights granted on `/`, a process that
//! creates its own user + mount namespace and then calls `mount(NULL, "/",
//! NULL, MS_REC|MS_PRIVATE, NULL)` gets `EPERM`; without the domain, the same
//! sequence returns 0.
//!
//! So an app inside a realm cannot run a **nested sandbox that mounts**.
//! `bubblewrap` is the one that matters in practice -- measured: `bwrap
//! --unshare-all ...` fails at its first `mount` with "Failed to make /
//! slave: Operation not permitted" under any domain, and succeeds without
//! one. GTK's `glycin` image loaders spawn exactly that, so a GTK app that
//! must decode an SVG icon inside a realm decodes it **unsandboxed**. This is
//! published in `docs/book/src/limits.md`; it is a property of the mechanism,
//! not of the grant table below, and widening the grants cannot touch it.
//!
//! **What the app *receives* is decided one step earlier, and not here.**
//! `main.rs`'s K9b (`deny_nested_user_namespaces`) writes `0` to the realm's
//! own `/proc/sys/user/max_user_namespaces`, so a nested sandbox is refused at
//! `unshare(CLONE_NEWUSER)` instead of at the `mount` this file's domain would
//! have refused. That takes nothing away -- a nested namespace under this
//! domain could not have mounted anything -- and it is what turns the paragraph
//! above from "the app aborts" into "the app degrades". Do not reason about
//! the abort from this file alone; the two steps are load-bearing together.
//!
//! **"Widening cannot touch it" is measured, not reasoned**, because it is the
//! first thing anyone reading this file will want to try. A process holding a
//! domain that handles the whole rung-9 mask and grants *every one of those
//! rights on `/`* -- strictly more than [`grants`] can ever produce, and more
//! than the realm-root grant #187 declined -- fails the identical `glycin`
//! decode with the identical message (Arch, kernel `7.1.8-arch1-3`, ABI 9,
//! 2026-08-14). The one filesystem denial this ruleset does contribute on that
//! path is `openat("/", O_DIRECTORY)` -> `EACCES`, which `glycin` logs and
//! continues past; it is not the abort. See [`grants`] for why that one is
//! refused anyway.
//!
//! What it costs is not hypothetical: until 2026-08-15 it took
//! `test_real_actuation.py` -- **`run.sh`'s named M1.4 actuation gate
//! (#108)** -- plus `test_real_gtk.py` and `test_real_firefox.py` **red at the
//! shipped default**. K9b closed that (all three re-measured green at the
//! shipped default, same box, 2026-08-15) by changing *which* error a nested
//! sandbox receives, not by restoring the mount. What survives, and what the
//! limits page still publishes under
//! `landlock-breaks-nested-image-sandboxes`, is that image decoding inside a
//! realm on such a host runs with **no sandbox around it**. No gate here is
//! skipped or exempted.
//!
//! # What this ruleset does not do
//!
//! It requests **no `handled_access_net`**. Rungs 4 and 10 scope TCP and UDP
//! bind/connect by port; the realm's own network namespace (P2.6.2, and
//! P2.7.1 after it) carries that claim structurally and far more completely,
//! since it covers UDP and raw sockets too. Naming the field here would imply
//! this ruleset is what confines a realm's network, and it is not.

use std::ffi::{CStr, CString};
use std::marker::PhantomData;
use std::os::fd::RawFd;

use vitrin_realm_init::{
    plan_rung, Config, LandlockRequest, Stage, IN_REALM_HOME, IN_REALM_RUNTIME_DIR, IN_REALM_SHIM,
};

use crate::{errno, Fail};

// ---------------------------------------------------------------------------
// The kernel's vocabulary, hand-spelled
// ---------------------------------------------------------------------------

/// `landlock_create_ruleset(2)`, `landlock_add_rule(2)`,
/// `landlock_restrict_self(2)`.
///
/// Uniform across architectures: the Landlock calls arrived in 5.13 through
/// the *generic* syscall table, unlike `seccomp`'s per-architecture
/// numbering. On an architecture without them the call answers `ENOSYS`,
/// which this module reports as a refusal rather than treating as "no
/// confinement needed".
const SYS_LANDLOCK_CREATE_RULESET: libc::c_long = 444;
const SYS_LANDLOCK_ADD_RULE: libc::c_long = 445;
const SYS_LANDLOCK_RESTRICT_SELF: libc::c_long = 446;

/// With a null attribute and a zero size this flag turns the create call into
/// a pure ABI query that creates nothing.
const LANDLOCK_CREATE_RULESET_VERSION: libc::c_uint = 1;

/// `LANDLOCK_RULE_PATH_BENEATH`. The only rule type this build adds.
const LANDLOCK_RULE_PATH_BENEATH: libc::c_uint = 1;

// The filesystem access rights, by the ABI rung that introduced them.
// Rung 1:
const EXECUTE: u64 = 1 << 0;
const WRITE_FILE: u64 = 1 << 1;
const READ_FILE: u64 = 1 << 2;
const READ_DIR: u64 = 1 << 3;
const REMOVE_DIR: u64 = 1 << 4;
const REMOVE_FILE: u64 = 1 << 5;
const MAKE_CHAR: u64 = 1 << 6;
const MAKE_DIR: u64 = 1 << 7;
const MAKE_REG: u64 = 1 << 8;
const MAKE_SOCK: u64 = 1 << 9;
const MAKE_FIFO: u64 = 1 << 10;
const MAKE_BLOCK: u64 = 1 << 11;
const MAKE_SYM: u64 = 1 << 12;
/// Rung 2. **Inverted, and the one rung whose absence is not a weakening.**
/// `REFER` is denied by *any* ruleset that does not handle it, so an ABI-1
/// domain is stricter about reparenting, not weaker: measured here, a
/// cross-directory `rename(2)` inside a fully granted hierarchy answers
/// `EXDEV` at rung 1 and succeeds from rung 2 up. Handling it is what lets
/// the realm rename across directories inside its own storage -- which is how
/// GTK and Firefox write files (atomic rename-into-place).
///
/// This is the whole reason the published invariant is "the cap reproduces an
/// ABI-N kernel", never "the cap only weakens".
const REFER: u64 = 1 << 13;
/// Rung 3. Without it a payload that cannot *write* a file can still destroy
/// it: `truncate(2)`, `creat(2)` and `O_TRUNC` are ungated below this rung.
const TRUNCATE: u64 = 1 << 14;
/// Rung 5. Gates `ioctl(2)` on opened character and block devices. A
/// documented set of generic commands (`FIOCLEX`, `FIONBIO`, `FIONREAD`, ...)
/// stays invokable regardless.
const IOCTL_DEV: u64 = 1 << 15;
/// Rung 9. Restricts `connect(2)` and addressed `sendmsg(2)` to **pathname**
/// UNIX sockets. Handling it without granting it on the shim's Wayland socket
/// path would stop the app reaching its display server, and the failure mode
/// is a black screen rather than a log line -- see [`grants`].
const RESOLVE_UNIX: u64 = 1 << 16;

/// Rung 6's `scoped` field: the domain cannot connect to an abstract UNIX
/// socket created outside it, and cannot signal a process outside it.
///
/// Both are also carried structurally by P2.6.2's namespaces -- abstract
/// sockets are per-netns, and the pid namespace already denies signalling
/// outward -- so this rung is defence in depth rather than the mechanism
/// behind either published claim.
const SCOPE_ABSTRACT_UNIX_SOCKET: u64 = 1 << 0;
const SCOPE_SIGNAL: u64 = 1 << 1;

/// `LANDLOCK_RESTRICT_SELF_LOG_NEW_EXEC_ON`, rung 7's second flag bit.
///
/// The kernel's default is to audit a domain's denials for the **current**
/// execution only and to fall silent across `execve`. This bit keeps the log
/// on afterwards, which is the only side of the `execve` where a realm's app
/// runs.
const LOG_NEW_EXEC_ON: libc::c_uint = 1 << 1;

/// The rung that first accepts [`LOG_NEW_EXEC_ON`]. Below it the flag is not
/// "ignored", it is `EINVAL` -- which would turn a diagnostic into a realm
/// that will not start.
const LOG_FLAGS_RUNG: u32 = 7;

/// The `flags` argument of `landlock_restrict_self`, which is **zero in every
/// shipped run**.
///
/// Rungs 7 and 8 buy flags here rather than mask bits: 7 is audit-log control
/// (`LOG_SAME_EXEC_OFF`, `LOG_NEW_EXEC_ON`, `LOG_SUBDOMAINS_OFF`) and 8 is
/// `TSYNC`. Neither is requested by a shipped session, and each absence has a
/// reason rather than being an oversight:
///
/// - **`TSYNC` (rung 8)** applies the domain to every thread of the calling
///   process. This binary is single-threaded by design (`main.rs` module
///   docs) and the ruleset is enforced on the one thread that then `execve`s,
///   so the helper's shape already carries what `TSYNC` would buy.
/// - **The log flags (rung 7)** are an observability lever, not a
///   confinement one; **no published claim depends on them**.
///   `LOG_NEW_EXEC_ON` is what makes the app's post-`execve` denials visible
///   to audit, which is the input P2.6.9's measured read/write set needs.
///   Since it is pure observability it is now reachable -- but only through
///   [`vitrin_realm_init::LANDLOCK_AUDIT_ENV`], a diagnostic the core forwards
///   only when its own environment carries it, never from `realm.toml`, never
///   from a command line, and never by default.
///
/// **What that costs the published ladder, stated rather than buried.** The
/// pages that say the enforced domain is byte-identical at rungs 6, 7 and 8
/// are describing the flags word being zero, which is true of every run that
/// does not set the diagnostic. Under the diagnostic, rung 7 and rung 6 differ
/// by exactly this bit -- and the difference is in what the *kernel logs*, not
/// in what it permits, so no confinement claim moves either way.
///
/// Because both are flags rather than mask bits, **their absence cannot be
/// simulated by the rung cap**: there is nothing to remove from a request that
/// never asked. Those two rungs are therefore prose-backed, as rung 4 is for
/// the same reason on the network side, and `docs/book/src/limits.md` says so
/// in the bullet that also states the byte-identical domains at 3/4 and at
/// 6/7/8. Since 2026-08-15 there **is** a generated ladder table --
/// `docs/book/src/isolation-matrix.md`, emitted by `cargo xtask
/// isolation-matrix` and held by CI -- and it renders these two rungs as
/// "capping simulates it: **no**" from this very function's shape. What that
/// table is *not* is a per-kernel measurement (see
/// `docs/plan/02-phase-2-semantic-epochs.md`, "P2.6.3, corrected",
/// Correction 5): it parses this file rather than probing a machine, so "the
/// published ladder" is now generated and gated, while the *values* behind each
/// rung's behaviour were recorded on one box on one date -- the tests that take
/// them run here and on the CI runner, whose job declares
/// `VITRIN_REQUIRE_LANDLOCK_ABI=7` so a skip is a panic, and on no third
/// machine.
fn restrict_self_flags(rung: u32, audit: bool) -> libc::c_uint {
    if audit && rung >= LOG_FLAGS_RUNG {
        LOG_NEW_EXEC_ON
    } else {
        0
    }
}

/// [`restrict_self_flags`], for the table test.
#[cfg(test)]
pub fn restrict_self_flags_for_test(rung: u32, audit: bool) -> libc::c_uint {
    restrict_self_flags(rung, audit)
}

/// `struct landlock_ruleset_attr`, as of the ABI this build knows.
///
/// Three fields, and the size passed to the kernel is **this build's own
/// `size_of`**, never a literal: the struct grows between ABI versions (rung
/// 10 adds three more `__u64`s). A smaller size than the running kernel's is
/// zero-filled by `copy_struct_from_user`; a larger one is accepted only if
/// the trailing bytes are zero, which is why [`create_ruleset`] treats
/// `E2BIG` as a rung to step down from rather than a hard failure.
#[repr(C)]
#[derive(Default)]
struct RulesetAttr {
    handled_access_fs: u64,
    handled_access_net: u64,
    scoped: u64,
}

/// `struct landlock_path_beneath_attr`, which the kernel declares
/// **`__attribute__((packed))`** -- 12 bytes, not 16.
#[repr(C, packed)]
struct PathBeneathAttr {
    allowed_access: u64,
    parent_fd: i32,
}

// ---------------------------------------------------------------------------
// The ladder
// ---------------------------------------------------------------------------

/// The cumulative `handled_access_fs` mask at one rung.
///
/// Every value here was verified empirically against this kernel rather than
/// recalled: `0x1fff`, `0x3fff`, `0x7fff`, `0xffff`, `0x1ffff` accepted;
/// `0x3ffff` (rung 10's) refused `EINVAL`.
///
/// **Four of the nine rungs do not move it at all** (4, 6, 7 and 8), and the
/// flatness is the honest picture of how much of the ABI ladder this ruleset
/// consumes -- it is shown rather than hidden. That sentence is **computed**,
/// not typed: `cargo xtask isolation-matrix` parses the ladder out of the
/// function below and refuses to emit unless this comment carries the count it
/// derives. The form it replaced was hand-written and had drifted -- it
/// counted ABI 10, a clamp row above this build's ceiling that never reaches
/// this function, as one of the rungs.
fn handled_access_fs(rung: u32) -> u64 {
    let mut mask = EXECUTE
        | WRITE_FILE
        | READ_FILE
        | READ_DIR
        | REMOVE_DIR
        | REMOVE_FILE
        | MAKE_CHAR
        | MAKE_DIR
        | MAKE_REG
        | MAKE_SOCK
        | MAKE_FIFO
        | MAKE_BLOCK
        | MAKE_SYM;
    if rung >= 2 {
        mask |= REFER;
    }
    if rung >= 3 {
        mask |= TRUNCATE;
    }
    if rung >= 5 {
        mask |= IOCTL_DEV;
    }
    if rung >= 9 {
        mask |= RESOLVE_UNIX;
    }
    mask
}

/// [`handled_access_fs`], for the table test. The mask is what a rung *is*,
/// so it is pinned rather than left to be re-derived from this file.
#[cfg(test)]
pub fn handled_access_fs_for_test(rung: u32) -> u64 {
    handled_access_fs(rung)
}

/// [`scoped`], for the same reason.
#[cfg(test)]
pub fn scoped_for_test(rung: u32) -> u64 {
    scoped(rung)
}

/// Rung 6's `scoped` mask. Zero below it, because a nonzero `scoped` on a
/// kernel whose `struct landlock_ruleset_attr` is shorter is `E2BIG`.
fn scoped(rung: u32) -> u64 {
    if rung >= 6 {
        SCOPE_ABSTRACT_UNIX_SOCKET | SCOPE_SIGNAL
    } else {
        0
    }
}

/// What was actually enforced.
///
/// [`vitrin_realm_init::plan_rung`] decides what to *ask* for; this is what
/// came back.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Enforced {
    /// The rung the ruleset was built at. `0` only when the session asked for
    /// no ruleset at all.
    pub rung: u32,
    /// What this kernel reported for its own ABI, so `rung < kernel_abi` is
    /// visible in one journal entry.
    ///
    /// `0` means **not measured**, which happens on exactly one path: a
    /// session that asked for no ruleset, where [`apply`] returns before
    /// issuing any syscall at all. It is not an ABI number -- Landlock ABI
    /// versions start at 1 -- and the core journals it as `null` rather than
    /// as a rung.
    pub kernel_abi: u32,
}

// ---------------------------------------------------------------------------
// The three syscalls
// ---------------------------------------------------------------------------

/// The kernel's own ABI number, or the errno that stopped the question being
/// asked.
///
/// Allocation-free.
pub fn kernel_abi() -> Result<u32, Fail> {
    // SAFETY: the null pointer and zero size are exactly what the version
    // query requires; the kernel reads neither.
    let rc = unsafe {
        libc::syscall(
            SYS_LANDLOCK_CREATE_RULESET,
            std::ptr::null::<libc::c_void>(),
            0usize,
            LANDLOCK_CREATE_RULESET_VERSION,
        )
    };
    if rc >= 1 {
        Ok(rc as u32)
    } else if rc == 0 {
        // Documented as impossible -- ABI versions start at 1 -- so a zero is
        // refused rather than quietly treated as rung 0.
        Err(Fail::with(Stage::Landlock, libc::EPROTO))
    } else {
        Err(Fail::at(Stage::Landlock))
    }
}

/// A live Landlock ruleset, together with **the rung the kernel created it
/// at**.
///
/// The rung is the kernel's answer and never the caller's request:
/// [`create_ruleset`] steps down on `EINVAL`/`E2BIG`, and what is recorded here
/// is where that walk stopped. It is the only thing in this tree that builds
/// one **holding a descriptor**, both fields are private, and there is no
/// constructor anywhere that takes a descriptor and a rung as two separate
/// arguments -- so a descriptor cannot be labelled with a rung it was not
/// created at. (The one other constructor, [`Ruleset::unopened`], exists in
/// test builds and holds no descriptor at all.)
///
/// That is the entire point of the type. Entering a domain needs an
/// [`Entering`]; an `Entering` holds one of these; and the ledger reads the
/// rung **off the ruleset it is handed**. Before this type existed, the rung
/// the ledger recorded and the rung the ruleset was built at were two numbers a
/// human kept in step.
pub struct Ruleset {
    fd: RawFd,
    /// The rung `landlock_create_ruleset` accepted -- not the rung asked for.
    rung: u32,
}

impl Ruleset {
    /// The descriptor, for [`add_path_rule`], which does not keep it.
    pub fn fd(&self) -> RawFd {
        self.fd
    }

    /// The rung this ruleset was **created** at.
    pub fn rung(&self) -> u32 {
        self.rung
    }

    /// A rung with **no descriptor**, for the ledger's own non-vacuity proofs.
    ///
    /// `landlock_restrict_self` on `-1` cannot enter a domain at any rung, so
    /// this is safe to hand to a [`RungsEntered`] on a machine that has no
    /// Landlock at all -- which is what both of the ledger's `#[should_panic]`
    /// proofs in `main.rs` need, one per direction:
    /// `a_ledger_asked_for_a_rung_its_row_does_not_name_refuses_to_mint` for
    /// the mint check, and
    /// `a_ledger_that_skipped_a_rung_its_row_declares_fails_on_drop` for the
    /// converse still held in `Drop`. Those two are the only reason this
    /// exists. It is deliberately **not** a way to attach a chosen rung to a
    /// real descriptor: there is no argument here that could carry one.
    #[cfg(test)]
    pub fn unopened(rung: u32) -> Ruleset {
        Ruleset { fd: -1, rung }
    }
}

impl Drop for Ruleset {
    /// Close the descriptor.
    ///
    /// After `landlock_restrict_self` the domain is enforced and the descriptor
    /// is inert, and a measurement body that never got that far is a descriptor
    /// nothing else will close: `main.rs` builds one per measurement, in the
    /// parent, in a loop. `close` is async-signal-safe, so this keeps the
    /// module's allocation-free contract.
    fn drop(&mut self) {
        if self.fd >= 0 {
            // SAFETY: this value's own descriptor, handed out only as a
            // `RawFd` to `add_path_rule` and to the one syscall below.
            unsafe { libc::close(self.fd) };
        }
    }
}

/// Create a ruleset at `rung`, stepping **down** on `EINVAL`/`E2BIG` until the
/// kernel accepts one or the floor is reached.
///
/// # The floor, and why the descent still exists at all
///
/// Since the ABI floor landed (`LANDLOCK_MIN_ABI`, owner's decision 2026-08-15)
/// a shipped session never reaches this function below the floor: [`apply_with`]
/// refuses first, and the core refuses before that. The descent is kept for two
/// narrower reasons, and it bottoms out at `min(rung, LANDLOCK_MIN_ABI)`:
///
/// - a kernel may report ABI N and still refuse rung N's `handled_access_fs`
///   (a build without some right compiled in). One step down is a diagnosis;
///   walking to rung 1 would be the silent degradation the floor exists to end.
/// - `--landlock=abi:N` **is** allowed below the floor, because it is the
///   instrument the per-rung tests drive (`main.rs`'s rung measurements call
///   this directly). A request below the floor is taken literally and is never
///   walked down further -- there is nothing below it worth reaching.
///
/// The fallback is never masked: what comes back is a [`Ruleset`] carrying the
/// rung the kernel accepted, and every caller journals it.
///
/// Allocation-free, so a forked child may call it -- though `main.rs`'s
/// measurement bodies call it in the **parent** and let the forked child
/// inherit the descriptor, because that is what lets the ledger read the rung
/// off the ruleset itself instead of being told one; see [`Entering`].
pub fn create_ruleset(rung: u32) -> Result<Ruleset, Fail> {
    // A caller asking below the floor means it: the cap flag, driving a
    // measurement. A caller asking at or above it may descend to the floor and
    // no further.
    let bottom = rung.min(vitrin_realm_init::LANDLOCK_MIN_ABI);
    let mut rung = rung;
    loop {
        let attr = RulesetAttr {
            handled_access_fs: handled_access_fs(rung),
            // Deliberately zero; see this module's docs.
            handled_access_net: 0,
            scoped: scoped(rung),
        };
        // SAFETY: `attr` is a live, fully initialized struct and the size
        // passed is this build's own `size_of` for it.
        let rc = unsafe {
            libc::syscall(
                SYS_LANDLOCK_CREATE_RULESET,
                &attr as *const RulesetAttr,
                std::mem::size_of::<RulesetAttr>(),
                0 as libc::c_uint,
            )
        };
        if rc >= 0 {
            return Ok(Ruleset {
                fd: rc as RawFd,
                rung,
            });
        }
        let err = errno();
        // `EINVAL` is a mask bit this kernel does not know; `E2BIG` is a
        // trailing struct field it does not have. Both mean "one rung too
        // high", and both are recoverable by stepping down as far as the floor.
        // Anything else -- `ENOSYS` on a kernel without Landlock, `EPERM` from
        // an LSM above it -- is a refusal, because retrying it would only
        // produce the same answer at every rung.
        if (err == libc::EINVAL || err == libc::E2BIG) && rung > bottom {
            rung -= 1;
            continue;
        }
        return Err(Fail::with(Stage::Landlock, err));
    }
}

/// Grant `rights` on the hierarchy beneath `path`.
///
/// `rights` is masked by the rung's `handled_access_fs` at the call site: a
/// rule naming a bit the ruleset does not handle is `EINVAL`.
///
/// Allocation-free.
pub fn add_path_rule(ruleset: RawFd, path: &CStr, rights: u64) -> Result<(), Fail> {
    if rights == 0 {
        return Ok(());
    }
    // `O_PATH`, so the descriptor is a handle on the name and not on the
    // file's contents: it opens a directory this process may not read, and it
    // does not consume a file description the app could inherit anything
    // from. `O_CLOEXEC` because K13 only *marks* descriptors, and a rule fd
    // that reached the app would be a handle the ruleset does not cover.
    // SAFETY: `path` is a live NUL-terminated string.
    let fd = unsafe { libc::open(path.as_ptr(), libc::O_PATH | libc::O_CLOEXEC) };
    if fd < 0 {
        return Err(Fail::at(Stage::Landlock));
    }
    let attr = PathBeneathAttr {
        allowed_access: rights,
        parent_fd: fd,
    };
    // SAFETY: `attr` is a live packed struct of exactly the kernel's layout.
    let rc = unsafe {
        libc::syscall(
            SYS_LANDLOCK_ADD_RULE,
            ruleset,
            LANDLOCK_RULE_PATH_BENEATH,
            &attr as *const PathBeneathAttr,
            0 as libc::c_uint,
        )
    };
    let err = errno();
    // SAFETY: `fd` is this function's own descriptor and is used nowhere else.
    unsafe { libc::close(fd) };
    if rc < 0 {
        return Err(Fail::with(Stage::Landlock, err));
    }
    Ok(())
}

/// The **ruleset** a caller has committed to entering a Landlock domain with,
/// and the only thing [`restrict_self`] accepts.
///
/// # The published absolute this exists to hold
///
/// `docs/book/src/limits.md` publishes *"No test in this repository enters a
/// Landlock domain at rung 4 or rung 5"*, and the matrix page publishes a
/// per-rung list of the tests that enter one. Until this token existed, the
/// binding between a test and the rungs it enters was `RungsEntered`, which
/// every measurement in `main.rs` **opted into**. An opt-in cannot hold an
/// absolute about tests nobody has written yet: a new test that called
/// `create_ruleset(4)`, then `restrict_self`, and never touched the ledger
/// left that sentence false with `cargo xtask isolation-matrix --check`,
/// `limits-check` and the whole suite green. The generator held
/// declared-name -> real fn, declared-rung -> row and row -> declared rung,
/// and none of those three can see a domain nobody declared.
///
/// So the opt-in is gone. `landlock_restrict_self` is the only syscall that
/// enters a domain, [`restrict_self`] is the only place in this workspace that
/// issues it, and it now demands this token -- which, in a test build, only
/// [`RungsEntered::entering`] can mint. The production mint is compiled
/// **out** of test builds ([`Entering::production`]), so [`apply_with`]'s own
/// path to a domain is not a way around the ledger either; see
/// [`enter_domain`].
///
/// # And it carries the ruleset, not a number beside it
///
/// The first shape of this type held a `u32` the ledger was **told**, and that
/// left the absolute one line short. `entered.entering(1)` beside
/// `create_ruleset(4)` recorded rung 1, entered a rung-4 domain, and every
/// mechanism above stayed green: the ledger compared a number the test typed
/// against a table the same test named, and neither of them was the ruleset.
/// That was not a hypothetical -- the counterexample compiled. Each
/// measurement body papered over it with a line of its own
/// (`let rung = entering.rung();`), which is the remembered discipline this
/// ledger exists to replace.
///
/// It now holds the [`Ruleset`] itself, [`RungsEntered::entering`] reads the
/// rung **off** it, and [`restrict_self`] takes nothing else. The rung recorded
/// and the rung the enforced descriptor was created at are therefore one value
/// rather than two that agree -- there is no argument left for them to disagree
/// in, and the disagreement is now a type error rather than a green run.
///
/// # And it borrows the LEDGER, so the ledger cannot be forgotten under it
///
/// The second shape still left one route open, and it was again found by
/// compiling it rather than by reading. The token borrowed the *ruleset* and
/// nothing else, so this compiled and ran:
///
/// ```ignore
/// let entered = RungsEntered::for_test("a_realm_can_write_where_it_was_granted_and_nowhere_else");
/// let ruleset = create_ruleset(4).expect("a rung-4 ruleset");
/// let entering = entered.entering(&ruleset);
/// std::mem::forget(entered);      // the comparison in `Drop` never runs
/// // ... enter a rung-4 domain with `entering`, and every gate stays green
/// ```
///
/// Two changes close it, and they are load-bearing in different ways:
///
/// - [`RungsEntered::entering`] takes `&'a self` and this token carries a
///   `PhantomData<`[`LedgerBorrow`]`<'a>>`, so the ledger is **borrowed for as
///   long as the token lives**. The `mem::forget` above is now `E0505`,
///   pasted in `docs/book/src/limits.md`.
/// - The comparison against `BEHAVIOURAL_RUNGS` moved **into the mint**, in
///   the direction the published absolute is about. `entering` refuses a rung
///   the test's row does not declare *before* it returns a token, so the
///   sentence "no test enters a domain at rung 4 or rung 5" no longer rests on
///   a destructor at all. What is still in `Drop` is the other direction --
///   rungs a row declares that the run never entered -- and `Drop` is
///   skippable in Rust by construction (`mem::forget`, `ManuallyDrop`,
///   `Box::leak`, `process::exit`, `panic = "abort"`). That residual is
///   published rather than argued away; see `docs/book/src/limits.md`.
///
/// What neither covers is said in the same place: a test that asks the
/// *shipped* helper for a rung never links this module at all (held at
/// `crates/vitrin-core`'s realm spawn, `RUNGS_NO_TEST_ENTERS`), and a test that
/// issues syscall 446 by hand is held by nothing in this file.
#[derive(Clone, Copy)]
pub struct Entering<'a> {
    ruleset: &'a Ruleset,
    /// The ledger's borrow, carried so the type itself says what it holds.
    ///
    /// Zero-sized, and it changes no run. Its whole job is to keep
    /// [`RungsEntered::entering`]'s `&'a self` from being "simplified" back to
    /// `&self` by someone reading this struct and seeing only a ruleset in it.
    ledger: PhantomData<LedgerBorrow<'a>>,
}

/// What [`Entering`] borrows besides the ruleset.
///
/// In a test build that is the ledger; in a shipped build [`RungsEntered`] does
/// not exist, and the production mint has no ledger to borrow.
#[cfg(test)]
type LedgerBorrow<'a> = &'a RungsEntered;
/// See the `cfg(test)` twin: outside a test build there is no ledger.
#[cfg(not(test))]
type LedgerBorrow<'a> = &'a ();

impl<'a> Entering<'a> {
    /// The rung the ruleset about to be entered was **created** at.
    fn rung(self) -> u32 {
        self.ruleset.rung
    }

    /// The production mint, and its `cfg` is the load-bearing half.
    ///
    /// In a test build this function does not exist, so nothing outside
    /// [`RungsEntered`] can produce an [`Entering`] -- which is what makes the
    /// ledger mandatory rather than conventional. It takes the ruleset it is
    /// about to enter, so there is no rung to supply here either.
    #[cfg(not(test))]
    fn production(ruleset: &'a Ruleset) -> Entering<'a> {
        Entering {
            ruleset,
            ledger: PhantomData,
        }
    }
}

/// Every rung a test actually entered a Landlock domain at, recorded as the
/// token is minted and checked against `BEHAVIOURAL_RUNGS` when the ledger
/// drops.
///
/// # Which half is in `Drop`, which half is not, and why the split
///
/// The comparison used to be a method a test called last -- `matches_declaration`
/// at the bottom of four tests, invisible to every gate if a fifth omitted it.
/// That moved into `Drop`, which runs whether a test remembers or not. But
/// `Drop` is not *guaranteed* to run: `mem::forget`, `ManuallyDrop`,
/// `Box::leak`, `process::exit` and `panic = "abort"` each skip it, and the
/// first of those was demonstrated against this very type (see [`Entering`]).
/// A published absolute may not rest on a destructor.
///
/// So the two directions live in two places:
///
/// - **entered ⊆ declared** -- the direction `docs/book/src/limits.md`'s
///   *"No test in this repository enters a Landlock domain at rung 4 or rung 5"*
///   is about -- is asserted in [`RungsEntered::entering`], **before the token
///   exists**. Nothing done to the ledger afterwards can skip it.
/// - **declared ⊆ entered** -- a row claiming a rung the run never entered --
///   is asserted here in `Drop`, and is therefore skippable by the five
///   constructs above. It is a *staleness* check, and the limits page names it
///   as destructor-dependent rather than letting the absolute above cover it.
///
/// The ledger cannot be dropped early under a live token either:
/// [`RungsEntered::entering`] borrows `&'a self`, so `mem::forget(entered)`
/// between the mint and the use is a borrow-check error.
///
/// The ledger is constructed with the test's own name and looks its row up at
/// once, so a typo is a failure at construction rather than a comparison
/// against nothing. Construct it **after** any `skip_unless!`: a skipped test
/// returns before it enters anything, and a ledger dropped with an empty set
/// is a test that declared rungs it did not enter -- which is what this is
/// for.
///
/// The forked measurement bodies do not disturb it: a child reaches `_exit`,
/// which runs no destructor, and the parent's recording happened before the
/// `fork` because the token is minted there.
#[cfg(test)]
pub struct RungsEntered {
    /// The `#[test] fn`'s own name, as `BEHAVIOURAL_RUNGS` spells it.
    test: &'static str,
    /// Every rung handed to [`RungsEntered::entering`], in mint order.
    entered: std::cell::RefCell<Vec<u32>>,
}

#[cfg(test)]
impl RungsEntered {
    /// A ledger for `test`, which `BEHAVIOURAL_RUNGS` must already declare.
    pub fn for_test(test: &'static str) -> RungsEntered {
        assert!(
            crate::tests::BEHAVIOURAL_RUNGS
                .iter()
                .any(|(name, _)| *name == test),
            "{test} opened a Landlock domain ledger and BEHAVIOURAL_RUNGS does not declare it. \
             Add a row: `cargo xtask isolation-matrix` publishes which rungs are exercised, and \
             a test missing from that table is a rung published as measured by nothing"
        );
        RungsEntered {
            test,
            entered: std::cell::RefCell::new(Vec::new()),
        }
    }

    /// Record the rung `ruleset` was **created** at, refuse a rung this test's
    /// row does not declare, and mint the token [`restrict_self`] demands for
    /// that ruleset.
    ///
    /// The rung is read off the ruleset rather than handed in beside it, and
    /// that is the whole difference from the shape this replaced. A ledger that
    /// is *told* a number records what a test said; this one records what the
    /// kernel built. `entering(1)` next to a rung-4 ruleset is no longer a
    /// sentence this API can express.
    ///
    /// # Two things this signature does that a shorter one did not
    ///
    /// **`&'a self`, not `&self`.** The returned token carries the ledger's
    /// borrow ([`Entering::ledger`]), so the ledger cannot be moved -- and
    /// therefore cannot be `mem::forget`ten -- while a token minted from it is
    /// alive. Before that, the counterexample in [`Entering`]'s docs compiled
    /// and ran.
    ///
    /// **The declaration is checked here, not only in [`Drop`].** A destructor
    /// is skippable in Rust by construction, so an absolute that rests on one
    /// is an absolute with a documented hole. This assertion fires *before* the
    /// token exists, so a rung `BEHAVIOURAL_RUNGS` does not declare for this
    /// test cannot reach `landlock_restrict_self` however the ledger is
    /// disposed of afterwards. `Drop` keeps the converse -- a declared rung the
    /// run never entered -- and that half is the one the limits page publishes
    /// as destructor-dependent.
    pub fn entering<'a>(&'a self, ruleset: &'a Ruleset) -> Entering<'a> {
        let rung = ruleset.rung;
        let declared = self.declared();
        assert!(
            declared.contains(&rung),
            "{} is about to enter a Landlock domain at rung {rung}, and BEHAVIOURAL_RUNGS \
             declares {declared:?} for it. That table is what `cargo xtask isolation-matrix` \
             publishes as the rungs each test enters, and `docs/book/src/limits.md` states an \
             absolute about the rungs no test enters at all -- so a rung reached here and \
             missing from the row is a published sentence about to become false. Add the rung \
             to the row if the retarget was intended, and expect the matrix page and the limits \
             page to change with it",
            self.test
        );
        self.entered.borrow_mut().push(rung);
        Entering {
            ruleset,
            ledger: PhantomData,
        }
    }

    /// This ledger's row in `BEHAVIOURAL_RUNGS`.
    ///
    /// [`RungsEntered::for_test`] already refused a name the table does not
    /// carry, so the lookup cannot miss here.
    fn declared(&self) -> &'static [u32] {
        crate::tests::BEHAVIOURAL_RUNGS
            .iter()
            .find(|(name, _)| *name == self.test)
            .expect("checked in `for_test`")
            .1
    }
}

#[cfg(test)]
impl Drop for RungsEntered {
    fn drop(&mut self) {
        // A failing assertion inside the test has already said what is wrong,
        // and a second panic while unwinding aborts the process without
        // printing it.
        if std::thread::panicking() {
            return;
        }
        let mut seen = self.entered.borrow().clone();
        seen.sort_unstable();
        seen.dedup();
        let declared = self.declared();
        // `entering` already refused anything outside `declared`, so what is
        // left for this comparison to catch is a rung the row declares and the
        // run never reached. It is written as an equality anyway: the message
        // is the useful one, and an equality that can only fail one way is
        // cheaper to read than a subset test plus a comment saying why the
        // other direction is impossible.
        assert_eq!(
            seen, declared,
            "{} entered Landlock domains at {seen:?} and BEHAVIOURAL_RUNGS declares \
             {declared:?}. The declaration is what `cargo xtask isolation-matrix` publishes as \
             this test's rungs, so the two have to move together -- update the table if the \
             retarget was intended, and expect the matrix page and `docs/book/src/limits.md` to \
             change with it",
            self.test
        );
    }
}

/// Enter the domain from the **production** path, and refuse to from a test.
///
/// Two bodies. The shipped one mints an [`Entering`] and calls
/// [`restrict_self`]; the `cfg(test)` one panics, because a test that reached
/// this line would have entered a Landlock domain at whatever rung
/// [`apply_with`] planned without passing through [`RungsEntered`] -- the one
/// remaining way around the ledger, and the reason this function exists rather
/// than a bare call. No test drives `apply_with` that far today: the two that
/// call it stop at `--landlock=off` and at a probe answering `ENOSYS`.
#[cfg(not(test))]
fn enter_domain(ruleset: &Ruleset, flags: libc::c_uint) -> Result<(), Fail> {
    restrict_self(Entering::production(ruleset), flags)
}

#[cfg(test)]
fn enter_domain(ruleset: &Ruleset, _flags: libc::c_uint) -> Result<(), Fail> {
    let rung = ruleset.rung();
    panic!(
        "landlock::apply_with reached `landlock_restrict_self` at rung {rung} under `cargo \
         test`. The production path may not enter a Landlock domain in a test build: the rungs \
         a test enters are published per rung on docs/book/src/isolation-matrix.md and as an \
         absolute on docs/book/src/limits.md, and only `RungsEntered` records them. Drive the \
         rung through a forked measurement body with a ledger, or change what those two pages \
         say first."
    )
}

/// Enforce the ruleset on this process and every descendant.
///
/// Requires `PR_SET_NO_NEW_PRIVS`, which K10 has already set. Irreversible by
/// construction: there is no call that removes a Landlock domain.
///
/// The ruleset arrives **inside** `entering` rather than beside it, and that is
/// what makes the recording exact: the descriptor this syscall is handed is the
/// descriptor the ledger was handed, and the rung the ledger wrote down is the
/// rung that descriptor was created at. No caller can reach this syscall
/// without having gone through a mint, and no caller can name a rung here at
/// all; see [`Entering`].
///
/// `flags` is [`restrict_self_flags`]' answer -- zero for every shipped
/// session. It is a parameter rather than a constant read in here so that the
/// forked measurement bodies in `main.rs`'s tests, which drive this function
/// directly, name the flags word they are measuring instead of inheriting one.
///
/// Allocation-free.
pub fn restrict_self(entering: Entering<'_>, flags: libc::c_uint) -> Result<(), Fail> {
    // The rung is not sent to the kernel -- it is already baked into the
    // ruleset -- so this reads it for the one invariant it can state, rather
    // than leaving it unread in a shipped build.
    debug_assert!(
        entering.rung() >= 1,
        "a Landlock domain cannot be entered at rung 0: rung 0 is `--landlock=off`, which builds \
         no ruleset at all"
    );
    // SAFETY: an integer descriptor and a flags word.
    let rc = unsafe { libc::syscall(SYS_LANDLOCK_RESTRICT_SELF, entering.ruleset.fd, flags) };
    if rc < 0 {
        return Err(Fail::at(Stage::Landlock));
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// The grant table
// ---------------------------------------------------------------------------

/// Read and list a hierarchy, with **no** right to execute anything in it.
const READ_ANY: u64 = READ_FILE | READ_DIR;

/// Read, list and execute: a hierarchy the realm runs code out of.
const READ_EXEC: u64 = READ_FILE | READ_DIR | EXECUTE;

/// Read and execute a **regular file**, and the missing bit is load-bearing.
///
/// `LANDLOCK_ACCESS_FS_READ_DIR` on a regular file is not an unused right, it
/// is an **`EINVAL` from `landlock_add_rule`** -- measured on this box (ABI 9,
/// 2026-08-14). Every rule that may name a file is `required`, and [`apply`]
/// fails closed, so one such rule takes the whole realm down at the shipped
/// default. `main.rs`'s `a_bind_naming_a_file_gets_rights_the_kernel_accepts`
/// re-measures both halves on every run.
const READ_EXEC_FILE: u64 = READ_FILE | EXECUTE;

/// Everything a realm may do inside a hierarchy it owns.
///
/// **`MAKE_CHAR` and `MAKE_BLOCK` are deliberately absent.** A realm has no
/// business minting device nodes; it also holds no `CAP_MKNOD`, so the
/// syscall would fail anyway -- stating it as a rule turns a side effect of
/// the credential drop into a property of the ruleset, which survives a
/// future tier that hands the realm more capability.
///
/// `RESOLVE_UNIX` travels with every writable hierarchy because a socket the
/// realm creates for itself must stay connectable to it: the shim's
/// `wayland-0`, the reserved accessibility-bus path, and whatever an app
/// binds in its own `/tmp`.
const WRITE_TREE: u64 = READ_FILE
    | READ_DIR
    | WRITE_FILE
    | TRUNCATE
    | REFER
    | REMOVE_DIR
    | REMOVE_FILE
    | MAKE_DIR
    | MAKE_REG
    | MAKE_SOCK
    | MAKE_FIFO
    | MAKE_SYM
    | RESOLVE_UNIX;

/// One granted hierarchy.
struct Grant {
    path: CString,
    rights: u64,
    /// A path that must exist. Everything the **core** named in the config is
    /// required, because the core bound it; only the host-shape-dependent
    /// `/bin`-class compatibility names are optional, since a merged-`/usr`
    /// machine and a split-`/usr` one disagree about which exist.
    required: bool,
}

fn grant(path: &str, rights: u64, required: bool) -> Result<Grant, Fail> {
    Ok(Grant {
        path: CString::new(path).map_err(|_| Fail::with(Stage::Landlock, libc::EINVAL))?,
        rights,
        required,
    })
}

/// **An enumerated read set, with a narrower execute half inside it** (issue
/// #187).
///
/// Every right this ruleset grants is named against one hierarchy. There is no
/// rule on the realm root, which is what makes a path the mount table happened
/// to leave reachable -- `/`, `/run`, `/vitrin`, the `$HOME` stub a bind target
/// needed -- answer `EACCES` rather than opening.
///
/// # A broad read grant at `/` was tried, measured, and reverted
///
/// It is the obvious widening, so the result is recorded here rather than left
/// to be rediscovered. Replacing this enumeration with a single
/// `READ_FILE|READ_DIR` rule on `/`:
///
/// - **takes #186's shipped acceptance gate red.** A `READ_DIR` rule on `/`
///   covers every directory beneath it, so `test_real_confinement.py`'s
///   `/vitrin` denial and its `$HOME` canary both fail -- measured 2026-08-15,
///   two `AssertionError: 'ok' != 'fail'`.
/// - **buys no app compatibility at all**, which is the half that decides it.
///   The three real-app gates that were red at the shipped default until
///   2026-08-15 were red for a reason no grant reaches: a Landlock domain
///   refuses `mount(2)` unconditionally, `bwrap` died at its first mount, and
///   GTK's image loader aborted. Measured with the broad grant in place: the
///   same abort. Measured with **every rung-9 right granted on `/`** --
///   strictly more than either shape can produce: the same abort. What
///   repaired them was `main.rs`'s K9b, which is not a grant and is not in
///   this file. See this module's header and
///   `docs/book/src/limits.md`'s `landlock-breaks-nested-image-sandboxes`.
///
/// So the enumeration is kept, and what it is worth is stated exactly rather
/// than flatteringly: measured against `--landlock=off` it denies a handful of
/// **empty scaffolding directories** the realm's own mount table had to mint to
/// hold a bind target, plus `execve` anywhere under `/etc`. It denies no path
/// that carries data, because the mount table puts host content nowhere but at
/// a bind target and every bind target is granted. `docs/book/src/limits.md`
/// publishes that measurement with the same emphasis.
///
/// # The rule the exec grants follow
///
/// **Landlock's `EXECUTE` grant is exactly the mount table's `noexec` map, less
/// `/etc`.** Where `build_mount_table` permits execution, so does this --
/// `/usr`, the `/bin`-class compatibility names, the shim binary, the app's own
/// directory, the operator's `binds`, and `/tmp` (whose mount is deliberately
/// not `noexec`; see `build_mount_table`). Where the mount forbids it
/// (`/run/vitrin`, `/vitrin/home`, `/dev/shm`, `/proc`, `/sys`, `/dev`),
/// neither does this, so an argued mount flag is not quietly re-decided here.
///
/// `/etc` is the one place the two maps differ, deliberately: it is bound
/// `MS_RDONLY|MS_NOSUID|MS_NODEV` with **no** `noexec`, so the mount permits
/// execution there and only this ruleset refuses it. That single denial is what
/// this layer buys over the mount namespace on the execute axis, and adding
/// `/etc` to the execute set would give it away. **No test in this repository
/// measures it yet** -- said plainly rather than left implied, because an
/// unmeasured denial is prose.
///
/// # Each rule is a complete description of its own hierarchy
///
/// Landlock resolves an access by walking from the file up to the root and
/// clearing the requested rights against every rule it passes, so a file's
/// effective rights are the **union** of every matching ancestor's. With no
/// rule at the root, each row below is the whole of what its hierarchy carries
/// -- `/usr` says `READ_FILE|READ_DIR|EXECUTE`, and a path under it gets
/// exactly that.
///
/// Two rows are a **file** rather than a hierarchy -- the shim binary, and any
/// `binds` entry naming one -- and they carry [`READ_EXEC_FILE`], because
/// `READ_DIR` on a regular file is refused by `landlock_add_rule` outright.
/// [`crate::bind_is_file`] is the one predicate that decides which kind a
/// `binds` entry is, shared with the mount table so the two cannot disagree
/// about what they built.
///
/// # `WRITE_FILE` on the whole of `/proc`, and why it cannot be narrower
///
/// `/proc` carries `WRITE_FILE` -- the right to write *through* an existing
/// file, with no `TRUNCATE`, no `MAKE_*`, no `REMOVE_*` and no `REFER`, so
/// nothing there can be created, deleted, renamed or emptied. The rule is on
/// the hierarchy root, which is broader than the paths any measured app
/// actually writes, and the reason is a property of Landlock rather than a
/// convenience:
///
/// - **A path rule is an `O_PATH` descriptor on one inode.** There is no glob,
///   no pattern and no late binding. To express "each process's own
///   `/proc/<pid>` and nothing else" this function would have to know the pids
///   of processes that do not exist yet -- the ruleset is built and enforced
///   *before* the shim's `execve`, and the app is a later child with a pid this
///   process never sees.
/// - **`/proc/self` is a symlink and `O_PATH` follows it.** A rule opened on
///   `/proc/self` here resolves to `/proc/1`, the helper's own directory, which
///   is precisely the one directory the app is not.
///
/// What the acceptance set actually writes there, measured by tracing the three
/// real-app gates inside a realm at `--landlock=off` (`strace -f -e
/// trace=%file`, 2026-08-14): `/proc/self/oom_score_adj` and
/// `/proc/self/coredump_filter`. Both are per-process knobs on the writer's own
/// task. Nothing in the acceptance set writes `/proc/sys/*` or another task's
/// entry.
///
/// What the breadth costs, stated rather than implied: the realm may write any
/// procfs file its **credentials** already permit -- and it has zero
/// capabilities, an identity uid map and its own pid namespace with a fresh
/// procfs, so that is its own tasks' knobs. `/proc/sys/*` is root-owned and
/// stays refused by DAC. The residual is real but it is bounded by the
/// credential drop, not by this rule, and a future tier that hands a realm more
/// capability must revisit this line rather than inherit it.
///
/// # `IOCTL_DEV`, and what rung 5 does *not* buy
///
/// It is granted on exactly two hierarchies: the **render nodes**, because an
/// app that cannot `ioctl` its render node cannot render at all, and
/// **`/dev/pts`**, because terminal `ioctl`s (`TCGETS`, `TIOCGWINSZ`,
/// `TIOCGPTN`) are how a pty is driven and `/dev/ptmx` is a symlink into it.
/// It is denied on `/dev/null`, `/dev/zero`, `/dev/full`, `/dev/random`,
/// `/dev/urandom`, `/dev/tty` and `/dev/shm`.
///
/// So this rung narrows the realm's device-`ioctl` surface to two paths --
/// and it **does not close the published render-node limit**. `IOCTL_DEV` is
/// one all-or-nothing bit per hierarchy, the app needs the node's `ioctl`s,
/// so the node keeps them. `limits.md`'s "the render node's ioctl surface and
/// the cross-realm GPU-memory side channels it carries are real and
/// unaddressed" survives this rung intact, and that page's ladder bullets say
/// so.
fn grants(config: &Config) -> Result<Vec<Grant>, Fail> {
    let mut out = Vec::new();

    // --- read + execute -----------------------------------------------------
    // `/usr` and the `/bin`-class compatibility names. On a merged-`/usr`
    // host the latter are symlinks into `/usr`, so their `O_PATH` open
    // resolves to a hierarchy `/usr`'s rule already covers and the extra rule
    // is a harmless duplicate; on a split-`/usr` host they are real
    // directories and the rule is the only thing granting them.
    out.push(grant("/usr", READ_EXEC, true)?);
    for name in crate::COMPAT_NAMES {
        out.push(grant(&format!("/{name}"), READ_EXEC, false)?);
    }
    // The shim binary itself -- a FILE bind, so no `READ_DIR` -- and it is the
    // one grant whose absence is a realm that will not start: `execve` is
    // checked against `EXECUTE` here.
    out.push(grant(IN_REALM_SHIM, READ_EXEC_FILE, true)?);
    if let Some(dir) = &config.app_dir {
        out.push(grant(&dir.to_string_lossy(), READ_EXEC, true)?);
    }
    for extra in &config.binds {
        // Operator-declared read-only binds. Their mounts are `RO_BIND` --
        // `MS_RDONLY | MS_NOSUID | MS_NODEV`, with no `noexec` -- so they
        // permit execution and the ruleset mirrors that rather than
        // re-deciding it. A `binds` entry may name a regular file
        // (`examples/realm.toml`: "a regular file or directory"), and the rule
        // for one may not name `READ_DIR`: `landlock_add_rule` refuses it
        // `EINVAL`, every bind is `required`, and `apply` fails closed, so the
        // wrong branch here is every realm on the box refusing to start.
        let rights = if crate::bind_is_file(extra) {
            READ_EXEC_FILE
        } else {
            READ_EXEC
        };
        out.push(grant(&extra.to_string_lossy(), rights, true)?);
    }

    // --- read only, no execute ----------------------------------------------
    // `/etc` is bound with no `noexec`, so the mount permits execution there
    // and withholding `EXECUTE` here is the one filesystem denial this layer
    // contributes that the mount table does not already carry. `/sys` is a
    // fresh, read-only, `noexec` sysfs; the ruleset states the same thing
    // rather than relying on the flag alone.
    out.push(grant("/etc", READ_ANY, true)?);
    out.push(grant("/sys", READ_ANY, true)?);

    // --- the realm's own writable set --------------------------------------
    // **FULL write authority** -- create, delete, rename, truncate -- on
    // exactly the four the mount table publishes as writable
    // (`{/run/vitrin, /vitrin/home, /tmp, /dev/shm}`), and no fifth. `/tmp`
    // additionally carries `EXECUTE`, because its mount deliberately does.
    //
    // This is **not** the whole set of hierarchies carrying a write right, and
    // four published surfaces once said it was. `/proc`, `/dev`, `/dev/pts`
    // and each render node below also get `WRITE_FILE` -- the right to write
    // *through* an existing file or node, with no `TRUNCATE`, no `MAKE_*`, no
    // `REMOVE_*` and no `REFER`, so nothing there can be created, deleted,
    // renamed or emptied. Eight hierarchies carry `WRITE_FILE`; four carry
    // [`WRITE_TREE`]. Any prose that collapses the two is wrong in the
    // flattering direction, which is why the distinction is written here
    // beside the code rather than only on the limits page.
    out.push(grant(IN_REALM_RUNTIME_DIR, WRITE_TREE, true)?);
    out.push(grant(IN_REALM_HOME, WRITE_TREE, true)?);
    out.push(grant("/tmp", WRITE_TREE | EXECUTE, true)?);
    out.push(grant("/dev/shm", WRITE_TREE, true)?);
    // A fresh procfs of the realm's own pid namespace. Writable because real
    // software writes its own `/proc/self/*` (`oom_score_adj`,
    // `coredump_filter`); no `TRUNCATE`, no `MAKE_*`, no `REMOVE_*`, because
    // procfs has no such operations and stating that is free -- and the
    // missing `TRUNCATE` is measurable, which is why it is a gate. See this
    // function's docs for why the rule cannot be narrower than the hierarchy.
    out.push(grant("/proc", READ_ANY | WRITE_FILE, true)?);

    // --- devices ------------------------------------------------------------
    // `/dev` itself is a read-only tmpfs after K4's remount, so `WRITE_FILE`
    // here is the right to write *through* a device node (`/dev/null`), never
    // the right to create one.
    out.push(grant("/dev", READ_ANY | WRITE_FILE, true)?);
    // The pty machinery, including `/dev/ptmx` (a symlink to `pts/ptmx`).
    out.push(grant("/dev/pts", READ_ANY | WRITE_FILE | IOCTL_DEV, true)?);
    // Each bound render node, by name. **No `READ_DIR`**: a render node is a
    // character device, not a directory, and the kernel's rule check refuses
    // any right outside its file set on a non-directory -- measured, `EINVAL`
    // from `landlock_add_rule` on this box (ABI 9, 2026-08-15), which is a
    // refused realm rather than an ignored bit. Same rule as the shim binary
    // and a file `binds` entry; this is the third of the three file rows.
    for node in &config.render_nodes {
        let Some(name) = node.file_name() else {
            return Err(Fail::with(Stage::Landlock, libc::EINVAL));
        };
        out.push(grant(
            &format!("/dev/dri/{}", name.to_string_lossy()),
            READ_FILE | WRITE_FILE | IOCTL_DEV,
            true,
        )?);
    }

    Ok(out)
}

/// [`grants`] flattened to `(path, rights)`, for the file-bind measurement.
///
/// The table is pure -- it issues no syscall but the `stat` behind
/// [`crate::bind_is_file`] -- so a test may build one for any `Config` and
/// then hand each row to the kernel itself, which is what
/// `a_bind_naming_a_file_gets_rights_the_kernel_accepts` does.
#[cfg(test)]
pub fn grants_for_test(config: &Config) -> Result<Vec<(CString, u64)>, Fail> {
    Ok(grants(config)?
        .into_iter()
        .map(|entry| (entry.path, entry.rights))
        .collect())
}

// ---------------------------------------------------------------------------
// K12b
// ---------------------------------------------------------------------------

/// Build, grant and enforce. Returns what was actually enforced.
///
/// **Fails closed.** A session that asked for a ruleset and cannot have one
/// is a refused spawn, never a realm that starts without it: the whole point
/// of D-020(6)'s floor is that confinement does not degrade silently. The one
/// legal way to get no ruleset is to ask for none.
pub fn apply(config: &Config) -> Result<Enforced, Fail> {
    apply_with(config, kernel_abi)
}

/// [`apply`], with the ABI query injected.
///
/// The seam exists for exactly one assertion, and it is not a convenience:
/// `Off` must short-circuit **before any syscall**, and on a kernel that has
/// Landlock -- every kernel this repo's tests run on -- a test cannot tell
/// "the query was skipped" from "the query succeeded". Passing the query in
/// lets the test hand over a probe that *records being called* and answers
/// `ENOSYS`, so moving the short-circuit back below the query turns the test
/// red instead of leaving it green on the only machines available.
///
/// # The bug this shape fixes
///
/// The first draft queried the ABI before reading the request. A kernel with
/// no Landlock at all answers `ENOSYS`, `kernel_abi` turns that into a
/// [`Fail`], and **every realm spawn died -- including the ones that had
/// asked for no ruleset**. `spawn/isolation.rs`'s `admit` deliberately waives
/// the floor for `--landlock=off`, so the flag existed, was documented as the
/// answer for such a machine, and did not work; the operator's only remaining
/// move was `--isolation=off`, which drops the namespaces too. The refusal
/// text on that path also named a ruleset nobody had asked for.
pub(crate) fn apply_with(
    config: &Config,
    kernel_abi: impl FnOnce() -> Result<u32, Fail>,
) -> Result<Enforced, Fail> {
    // **First, and above the syscall.** See this function's docs.
    if config.landlock == LandlockRequest::Off {
        return Ok(Enforced {
            rung: 0,
            // Not measured rather than zero-as-a-rung: nothing asked the
            // kernel anything, and the core renders this as `null`.
            kernel_abi: 0,
        });
    }
    let kernel_abi = kernel_abi()?;
    // **The floor, checked here as well as in the core.** The core's
    // `spawn::isolation::admit` refuses such a machine before any realm is
    // spawned, so reaching this arm means the core's probe and the helper's
    // disagreed -- a substituted core, or a kernel whose LSM set changed under
    // a running session. Refused rather than degraded, because a helper that
    // quietly built a rung-4 domain would be the one outcome D-020(6) forbids:
    // the realm would be confined less than the session's own journal says.
    if kernel_abi < vitrin_realm_init::LANDLOCK_MIN_ABI {
        eprintln!(
            "vitrin-realm-init: this kernel reports Landlock ABI {kernel_abi} and this build's \
             floor is ABI {}. Refusing the realm rather than enforcing a weaker domain than the \
             session claims. `--landlock=off` starts realms with NO ruleset and is not a remedy \
             for a kernel that could be upgraded.",
            vitrin_realm_init::LANDLOCK_MIN_ABI
        );
        return Err(Fail::with(Stage::Landlock, libc::EPROTO));
    }
    // [`vitrin_realm_init::Plan::clamped_by_build`] is not sent as a third
    // number, and does not need to be: the **core** recomputes the same plan
    // from `(kernel_abi, request)` through the same pure function, which is
    // what lets it tell a ladder fallback from an operator's cap and journal
    // the clamp. Sending a boolean the core can derive would be a second
    // opinion about one session.
    let plan = plan_rung(kernel_abi, config.landlock);
    let ruleset = create_ruleset(plan.rung)?;
    let rung = ruleset.rung();

    // The **diagnostic** flags word (see [`restrict_self_flags`]). Read from
    // this process's own environment, which the core populated from nothing
    // and then added exactly this one name to, and only when its own
    // environment carried it.
    //
    // Announced on stderr -- the realm's own log file -- in both directions,
    // because the failure mode of a diagnostic is silence: a measurement run
    // that quietly did not turn the log on reads exactly like a run that found
    // no denials. The second arm is the one that matters on a kernel below ABI
    // 7, where the bit is `EINVAL` rather than ignored, so the helper drops it
    // and says so instead of refusing the realm over an instrument.
    let audit = vitrin_realm_init::landlock_audit_requested(
        std::env::var(vitrin_realm_init::LANDLOCK_AUDIT_ENV)
            .ok()
            .as_deref(),
    );
    let flags = restrict_self_flags(rung, audit);
    if flags != 0 {
        eprintln!(
            "vitrin-realm-init: LANDLOCK AUDIT DIAGNOSTIC ON \
             ({}=1): landlock_restrict_self flags=0x{flags:x} \
             (LANDLOCK_RESTRICT_SELF_LOG_NEW_EXEC_ON) at rung {rung}. \
             The kernel will log this realm's denials AFTER the shim's execve. \
             The ruleset itself is unchanged.",
            vitrin_realm_init::LANDLOCK_AUDIT_ENV
        );
    } else if audit {
        eprintln!(
            "vitrin-realm-init: {}=1 asked for the Landlock audit diagnostic, \
             but this realm obtained rung {rung} and the log flags need rung \
             {LOG_FLAGS_RUNG}. Enforcing with flags=0; no post-execve denial \
             will be logged.",
            vitrin_realm_init::LANDLOCK_AUDIT_ENV
        );
    }

    let handled = handled_access_fs(rung);
    let result = (|| {
        for entry in grants(config)? {
            // Masked by the rung, because a rule naming an unhandled bit is
            // `EINVAL` -- which is also what makes a capped session behave
            // exactly like the older kernel it is imitating rather than
            // erroring differently.
            match add_path_rule(ruleset.fd(), &entry.path, entry.rights & handled) {
                Ok(()) => {}
                Err(fail) if !entry.required && fail.errno == libc::ENOENT => {}
                Err(fail) => return Err(fail),
            }
        }
        enter_domain(&ruleset, flags)
    })();
    // The descriptor closes with `ruleset` when this function returns, on both
    // paths: after `restrict_self` the domain is enforced and the descriptor is
    // inert, and on the error path the caller is about to `_exit`.
    result?;

    Ok(Enforced { rung, kernel_abi })
}
