"""vitrin_os — the pure-Python agent SDK for the Vitrin OS wire protocol.

A deliberately independent second implementation of the wire format
(spec v0, wire version 1): pure Python >= 3.11, stdlib only, no threads,
no async runtime, no C extension. See sdk/python/README.md.
"""

from .client import Connection, Frame, Grant, Realm, connect
from .errors import (
    AuthFailed,
    Busy,
    ConnectionClosed,
    ConsentHeld,
    ConsentTimeout,
    FatalError,
    FdViolation,
    GrantDenied,
    GrantExpired,
    GrantRefused,
    GrantResolutionError,
    GrantUnsupported,
    InternalError,
    InvalidArgument,
    InvalidObject,
    InvalidOpcode,
    NoSurface,
    NotGranted,
    ObjectIdsExhausted,
    OperationFailed,
    Oversized,
    Preempted,
    PreHandshake,
    RateLimited,
    RealmUnavailable,
    ResourceExhausted,
    Revoked,
    ServerContractViolation,
    VersionUnsupported,
    VitrinError,
)
from .protocol import (
    BTN_LEFT,
    BTN_MIDDLE,
    BTN_RIGHT,
    PROTOCOL_VERSION,
    Axis,
    ButtonState,
    ConsentState,
    ErrorCode,
    Format,
    FrameFlags,
    Outcome,
    Persistence,
    Refusal,
    Verb,
)

__version__ = "0.1.0a0"

__all__ = [
    "connect",
    "Connection",
    "Realm",
    "Grant",
    "Frame",
    # errors
    "VitrinError",
    "ConnectionClosed",
    "ServerContractViolation",
    "ObjectIdsExhausted",
    "FatalError",
    "InvalidObject",
    "InvalidOpcode",
    "InvalidArgument",
    "Oversized",
    "FdViolation",
    "PreHandshake",
    "VersionUnsupported",
    "AuthFailed",
    "InternalError",
    "ResourceExhausted",
    "GrantResolutionError",
    "GrantDenied",
    "ConsentTimeout",
    "RealmUnavailable",
    "GrantUnsupported",
    "Busy",
    "GrantRefused",
    "NotGranted",
    "GrantExpired",
    "Revoked",
    "RateLimited",
    "Preempted",
    "ConsentHeld",
    "NoSurface",
    "OperationFailed",
    # protocol constants
    "PROTOCOL_VERSION",
    "Verb",
    "Persistence",
    "Outcome",
    "Refusal",
    "ConsentState",
    "ErrorCode",
    "Format",
    "FrameFlags",
    "ButtonState",
    "Axis",
    "BTN_LEFT",
    "BTN_RIGHT",
    "BTN_MIDDLE",
]
